baseURL = 'http://blog-hugo-35d.pages.dev/'
languageCode = 'es-mx'
title = 'Blog Personal'
theme = "hugo-theme-m10c"

[params]
author = 'Samuel Villegas'
description = 'Blog hecho con Hugo por: Samuel Villegas. Estudiante de Informática.'
avatar = 'https://freesvg.org/img/1700575169Fox5b.png'

[[menu.main]]
  identifier = "tags"
  name = "Etiquetas"
  url = "/tags/"

[[menu.main]]
  identifier = "blog"
  name = "Entradas"
  url = "/posts/"



[[params.social]]
  icon = "github"
  name = "My Github"
  url = "https://github.com/vaga"

[[params.social]]
  icon = "twitter"
  name = "My Twitter"
  url = "https://github.com/vaga"

[[params.social]]
  icon = "phone"
  name = "My Telegram"
  url = "https://github.com/vaga"


[params.style]
  darkestColor = "#063970"
  darkColor = "#212121"
  lightColor = "#f5e3e0"
  lightestColor = "#f5f5f5"
  primaryColor = "#ffffff"