baseURL = 'http://blog-hugo-35d.pages.dev/'
languageCode = 'es-mx'
title = 'Blog Personal'
theme = "hugo-theme-m10c"

[params]
author = 'Samuel Villegas'
description = 'Blog hecho con Hugo por: Samuel Villegas. Estudiante de Informática.'
avatar = 'https://freesvg.org/img/1700575169Fox5b.png'

[[menu.main]]
  identifier = "tags"
  name = "Etiquetas"
  url = "/tags/"
  weight = 2

[[menu.main]]
  identifier = "blog"
  name = "Entradas"
  url = "/posts/"
  weight = 1

[[menu.main]]
  identifier = "about"
  name = "Acerca de"
  url = "/about/"
  weight = 3


[[params.social]]
  icon = "github"
  name = "My Github"
  url = "https://github.com/Samo9829"

[[params.social]]
  icon = "twitter"
  name = "My Twitter"
  url = "https://twitter.com/samoo_vr"

[[params.social]]
  icon = "phone"
  name = "My Telegram"
  url = "https://t.me/bearynice"


[params.style]
  darkestColor = "#315659"
  darkColor = "#253031"
  lightColor = "#96a879"
  lightestColor = "#fff"
  primaryColor = "#dad865"
